In [1]:
import numpy as np


In [2]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.random.rand(5,5)

array([[5.87104463e-02, 6.67932123e-01, 4.12338682e-01, 6.36784728e-01,
        6.55514239e-02],
       [9.63437817e-01, 2.83365500e-01, 9.60004524e-04, 9.10631030e-01,
        8.30283126e-01],
       [5.69137154e-01, 1.19212322e-01, 3.86421553e-01, 8.90226385e-01,
        1.78740376e-01],
       [1.04026104e-01, 9.96967006e-01, 6.80041850e-01, 7.79289289e-01,
        8.46080871e-01],
       [2.11648115e-01, 1.45963819e-01, 7.41926146e-01, 4.55760123e-01,
        5.51368317e-01]])

In [4]:
np.random.randint(1,100)

38

In [9]:
np.random.randint(36,size=(6,6))

array([[26, 21, 10, 30, 30,  3],
       [17, 16, 22, 26, 20, 33],
       [31, 18, 17, 11,  8, 31],
       [23, 12,  2, 24, 13,  7],
       [20, 21,  9,  0, 19,  8],
       [ 2,  0,  5, 14,  2,  0]])

# Arrays

In [10]:
arr= np.arange(25)

In [11]:
ranarr=np.random.randint(0,50,10)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# Reshape

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.reshape(5,5).shape

(5, 5)

# min,max,argmin,argmax

In [17]:
ranarr

array([46, 18, 21, 44,  9, 36, 29, 12, 14, 18])

In [18]:
ranarr.min()

9

In [20]:
ranarr.max() #max number

46

In [21]:
ranarr.argmin() #index of where min is located

4

In [22]:
ranarr.argmax() 

0

In [24]:
arr.dtype

dtype('int64')

In [25]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [28]:
arr.reshape(25,1).shape

(25, 1)